### PR TITLE
Add buildah trigger resources - tested on OCP 4.2

### PR DESCRIPTION
**Pull request by a-roberts**
All works

### CODE REVIEW

**Comment by a-roberts** [comment]
@dibbles for when you're ready please 😄 deployed a simple app fine based on a push using your Triggers code

**Comment by a-roberts** [comment]
Needs updating now https://github.com/pipeline-hotel/example-pipelines/pull/16 is in, doing other things atm

**Comment by a-roberts** [comment]
image

All good

**Comment by a-roberts** [comment]
@dibbles nudge 😅

**Review by dibbles — APPROVED** [review]

**Pull request merged**
